###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: wp-db
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - db_data:/var/lib/mysql

    webserver:
      image: nginx:alpine
      container_name: wp-web
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${HTTP_PORT}:80"
      depends_on: 
       - mariadb
       - php-fpm

    php-fpm:
      build: docker/php-fpm
      container_name: wp-php
      working_dir: /application
      volumes:
        - .:/application:rw
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:ro

volumes: 
  db_data: