###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      working_dir: /application
      volumes:
        - .:/application
        - db_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - ${MYSQL_PORT}:3306

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - ${HTTP_PORT}:80
      depends_on: 
       - mariadb
       - php-fpm

    php-fpm:
      build: docker/php-fpm
      working_dir: /application
      volumes:
        - .:/application:rw
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:ro

    webgrind:
      image: creativeprojects/webgrind
      ports:
        - ${WEBGRIND_PORT}:80
      volumes:
        - ./log:/tmp/xdebug:rw

volumes: 
  db_data: